DO $$ BEGIN
  CREATE TYPE "ProfissionalEstado" AS ENUM ('PENDENTE', 'APROVADO', 'REJEITADO');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'PROFISSIONAL';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "moradaFiscal" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "profissionalEstado" "ProfissionalEstado";
ALTER TABLE "Produto" ADD COLUMN IF NOT EXISTS "precoProfissional" DECIMAL(10,2);
ALTER TABLE "Produto" ADD COLUMN IF NOT EXISTS "quantidadeMinimaB2B" INTEGER NOT NULL DEFAULT 1;
